### ISSUE TITLE
Trying this patch with Windows Vista versions of card games slows down their animations instead of making those games smoother.

### ISSUE THREAD

**Issue by serega2004** [IntriguingTiles/Win7CardGames60FPS#1]
**Description**
This patch slightly slows down Windows Vista versions of card games and retains the default FPS instead of making them smoother.

**Steps to reproduce**
1. Install Windows Vista.
2. Install Visual C++ 2015 runtime.
3. Copy slc.dll and config.ini to folder of any card game in C:\Program Files\Microsoft Games.

**Expected behavior**
Games now run at 60 FPS.

**Actual behavior**
Games still run at the default FPS, but animations of them are now slower.

**Video**

https://github.com/IntriguingTiles/Win7CardGames60FPS/assets/66155894/793bb691-8411-427a-ad65-3a722a32864f

**Comment by IntriguingTiles** [comment]
Interesting, it looks there were some changes made to the engine between Vista and 7. `Timekeeping::InitializeTimekeeping` doesn't seem to exist in the Vista version.

**Comment by IntriguingTiles** [comment]
Actually, it looks like `Timekeeping::InitializeTimekeeping` does exist, but it's been inlined and doesn't actually work properly. It'll always fall back to the `timeGetTime` backend for timekeeping without even checking if the other backends work. My FPS patch only works for the `QueryPerformanceCounter` backend, so I'll need to add support for the other backends.

**Comment by serega2004** [comment]
Also, can you try making Hold 'Em run in 60 FPS? It's a card game that was a part of Windows Ultimate Extras for Windows Vista Ultimate.

**Comment by IntriguingTiles** [comment]
Probably not, it's on a different engine and there aren't any symbols for it on Microsoft's symbol server.

**Comment by IntriguingTiles** [comment]
I've released a new version which should support the Vista built-in card games.

**Comment by serega2004** [comment]
It works now, tysm!
